### ISSUE TITLE
Confirmation of person estimation result 

### ISSUE THREAD

**Issue by CGMikeG** [miu200521358/motion_trace_colab#19]
![Motion_Tracer_Colab](https://user-images.githubusercontent.com/65123386/135698962-210ab5bf-ce9f-4f9d-bdcb-7347230fe59a.JPG)

**Comment by miu200521358** [comment]
I can't figure out the cause from this error alone.
Please share your notebook.

**Comment by CGMikeG** [comment]
I have just shared note book with garnet200521358@gmail.com. I hope that's your email address :D. I am still getting familiar with Colab so I hope I've done it correctly.

**Comment by CGMikeG** [comment]
Thank you very much. It's working now.

**Comment by miu200521358** [comment]
It was good! have fun
