### ISSUE TITLE
pose smoothing with kalman filter

### ISSUE THREAD

**Issue by cyber9723470** [miu200521358/motion_trace_colab#24]
Thank you for the great work!

However, I found that in the produced vmd, the motion seems to be not very stable. 
I wonder if there is some noise or error in the joint detection results, or maybe the bounding box detection and cropping is not stable.

Is it possible to add smooth to detection results of the bounding box,  the 2D positions of the joints or the 3D positions of the joints? 
If these are possible already, could you give me some hints of how to adjust them? Thank you!

**Comment by miu200521358** [comment]
Thanks!

If the motion is left as it is, it will be a little rattling, so you can smooth it with "Motion Supporter".
(Currently only in Japanese. English will be supported in the future)

If you use "Smoothing" of "Motion Supporter", you can smooth the movement to some extent.

Please refer to the section below.
https://colab.research.google.com/github/miu200521358/motion_trace_colab/blob/master/MMDAutoTrace2_en.ipynb#scrollTo=o5BxR5tGM2k-

Thank you.

**Comment by cyber9723470** [comment]
Thanks a lot! Could you also show where the smoothing is done in the [Python code](https://github.com/miu200521358/expose_mmd)? I can have a try with differently level of smoothing myself :)

**Comment by cyber9723470** [comment]
https://github.com/digital-standard/ThreeDPoseTracker seems to use a [kalman filter](https://github.com/digital-standard/ThreeDPoseTracker/blob/8b87a85f68cdd1d764a98ac963ca471665acd4c5/Assets/Scripts/VNectBarracudaRunner.cs#L485) to smooth the joint position, and the result seems to be pretty good. 

Hope that is useful for you!
